# Generated by Django 5.2.5 on 2025-08-31 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование параметра')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('units', models.CharField(blank=True, max_length=20, null=True, verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код региона')),
                ('region_name', models.CharField(max_length=100, unique=True, verbose_name='Наименование региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='tep_api.parameter', verbose_name='Параметр')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='tep_api.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Значение параметра',
                'verbose_name_plural': 'Значения параметров',
                'unique_together': {('region', 'parameter')},
            },
        ),
    ]
